services:
  db:
    image: postgres:15
    container_name: check-jara-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: check_jara_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:10
    container_name: check-jara-flyway
    command: -url=jdbc:postgresql://db:5432/check_jara_db -user=user -password=password -connectRetries=60 migrate
    volumes:
      - ./db/sql:/flyway/sql
    depends_on:
      - db

  app:
    build: ./app
    container_name: check-jara-app
    volumes:
      - ./app:/app
      - ./logs:/logs
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/check_jara_db
    depends_on:
      db:
        condition: service_started
      flyway:
        condition: service_completed_successfully

  metabase:
    image: metabase/metabase:latest
    container_name: check-jara-metabase
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase.db
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase.db/metabase.db
    depends_on:
      - db

volumes:
  postgres_data:
  metabase_data:
